### ISSUE TITLE
Password Criteria Error Message Not Displaying at sign-up

### ISSUE THREAD

**Issue by tomgame984** [Seyi-Toluhi/The-Neurons#28]
When trying to create a new account on sign-up with the following details:

- First name: John
- Last name: Doe
- Email: john.doe@testemail.com
- password: Password
- neurodiversity: ASD

**Expected Result:** 
Error Message - Password has to have one of these symbols: !@$%&, at least 8 characters and a capital letter.
Password field to be cleared

**Actual Result:** 
No message displayed 
Password remains

**Comment by F-Gulmez** [comment]
Bug fix released
