### ISSUE TITLE
Password Error Message Misleading

### ISSUE THREAD

**Issue by tomgame984** [Seyi-Toluhi/The-Neurons#29]
Scenario: When trying to signup but providing an invalid password, the error shown in the terminal reads:

`Password has to have one of these symbols: !@$%&, at least 8 characters and a capital letter.`

It will be clearer for the user if the message reads something like:
"Invalid password.  The password criteria are:
- Minimum length: 8 Characters:
- Letters: At least one lowercase and one Uppercase
- Special Character: At least one of the following: ! @ $ % &

**Comment by F-Gulmez** [comment]
Bug fix released.
